site_name: IBDC-coursework
site_url: https://USERNAME.github.io/IBDC-coursework/

theme:
  name: material

nav:
  - Day 1: day1/index.md
  - Day 2: day2/index.md
  - Day 3: day3/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.mark

